language: php
php:
  - 8.0

services:
  - mysql

env:
  - MYSQL_DSN="mysql:host=localhost;dbname=sakila;user=root"

before_install:
  - sudo apt-get -qq update
  - mysql -u root < tests/Sakila/mysql-schema.sql
  - mysql -u root < tests/Sakila/mysql-data.sql

before_script:
  - composer self-update
  - composer install

script: vendor/bin/phpunit