name: Close Pull Request

on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: |
            👋 Thank you for your pull request!

            This repository is a read-only split from [hectororm/hectororm](https://github.com/hectororm/hectororm).

            **All contributions and PRs should be opened in the main repository.**

            _This PR will be closed automatically._
